language: python
sudo: false
cache: pip
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - PYPI_USER_NAME: chaostoolkit
    - secure: "pXir9Vubh2TPoD+P7fdJ7NbiHarMXd7Ix+uYCkVLyzofIBG5VgNZeWYXGmQl03aQzIGXvouIbeCHet+zjW5Lk1JmyOg1ZFT63tMnOYrh15QMWPapf1gdHsYhPXgTqW9yK+NGpxl4SdkqwHi1ZT+346hpkjxltIFzD/2VzoWMwGtDH0fxTB0eAmBGO2leKwphaedZltcBSWkjdm1qqWjEWr28dTx+Z9l+z+IrF1qHfmz1jCyzgvNVeFFm0EwldJUrwlWeIpZGbJ/Ty3wFGwSb8IsbTvB72+7Sbjl471wdvtMCZS1b/q2wnlA0nIE3GEt8l+mUDmFD8tOWcFNxHFiC/uwo9AZJlSKdG4ZddfE6NL7VwhZJXOfmeePSFvfWt3DtvFPyAq3YiT61gW8b8GTLOM3yVtUGhsG6tZ+JsnCsHkw5QuD9V2d0eLFwFTexFFsn+ICIN9ewByL1EBR0jN63n4X/8O1ZTw1NVgL99AFZmOYQCUMalp66kH88XMeeuCLyT43WUhKL0UmIx0i0bbW2HpnDyBM7DulOMHA5Ik7boJa0UWSV3rgg/QfFM+peF8MUdQGsQXnSCQEEeaBRf+3dcmCEb7Vk9NwbjG6VLuu9mrHL1ThM1bLrJbipWO7qu7LhLf3yByJPswnh20SlYwZEJm+PojGy1PB8np5+hJt4WEE="
python:
  - "3.6"
  - "3.7-dev"
install:
  - virtualenv --version
  - pip install -U pip setuptools
  - pip --version
  - pip install --pre -r requirements.txt -r requirements-dev.txt
script:
  - bash ci.bash
notifications:
  webhooks:
    urls:
    - "https://webhook.atomist.com/atomist/travis/teams/T76U4GPGF"
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always
